
export const IMG_UPLOAD_REQUEST = 'IMG_UPLOAD_REQUEST';
export const IMG_UPLOAD_BEGIN = 'IMG_UPLOAD_BEGIN';
export const IMG_UPLOAD_SUCCESS = 'IMG_UPLOAD_SUCCESS';
export const IMG_UPLOAD_FAILURE = 'IMG_UPLOAD_FAILURE';


export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_SUCCESS = 'GET_GALLERY_SUCCESS';


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';